"""Add TokenUsageLog table

Revision ID: 10b9e5d0f947
Revises: dceaa7e4494b
Create Date: 2026-07-03 17:48:54.165484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10b9e5d0f947'
down_revision = 'dceaa7e4494b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
