"""Add ChatTranscript table

Revision ID: 49e31aea00a0
Revises: b3877517faaa
Create Date: 2026-07-03 14:38:32.671072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49e31aea00a0'
down_revision = 'b3877517faaa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
