"""dynamic loan installments

Revision ID: 875961938e0d
Revises: dcf123456789
Create Date: 2026-07-11 19:38:46.541216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '875961938e0d'
down_revision = 'dcf123456789'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outreach_brain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('advice_text', sa.Text(), nullable=True),
    sa.Column('correction_log', sa.JSON(), nullable=True),
    sa.Column('generated_count', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outreach_brain', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outreach_brain_id'), ['id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('cycle', sa.String(), nullable=True),
    sa.Column('next_due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.Column('auto_deduct', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_id'), ['id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_installments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=True),
    sa.Column('amount_due', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loan_installments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loan_installments_id'), ['id'], unique=False)

    op.create_table('outreach_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_lead_id', sa.Integer(), nullable=False),
    sa.Column('generated_message', sa.Text(), nullable=False),
    sa.Column('edited_message', sa.Text(), nullable=True),
    sa.Column('was_edited', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_lead_id'], ['admin_leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outreach_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outreach_queue_id'), ['id'], unique=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_note_id'))

    op.drop_table('expenses')
    with op.batch_alter_table('crm_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delay_mode', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('auto_mode', sa.Boolean(), nullable=True))

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_column('installments_count')
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('installments_count', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('crm_settings', schema=None) as batch_op:
        batch_op.drop_column('auto_mode')
        batch_op.drop_column('delay_mode')

    op.create_table('expenses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('note_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_note_id'), ['note_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_id'), ['id'], unique=False)

    with op.batch_alter_table('outreach_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outreach_queue_id'))

    op.drop_table('outreach_queue')
    with op.batch_alter_table('loan_installments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loan_installments_id'))

    op.drop_table('loan_installments')
    op.drop_table('tasks')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('outreach_brain', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outreach_brain_id'))

    op.drop_table('outreach_brain')
    # ### end Alembic commands ###
