"""Initial migration with templates

Revision ID: b3877517faaa
Revises: 
Create Date: 2026-07-03 13:03:12.527013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3877517faaa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_outreach_run', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_settings', schema=None) as batch_op:
        batch_op.drop_column('next_outreach_run')

    # ### end Alembic commands ###
