"""Add TokenUsageLog table

Revision ID: bb4d823b7339
Revises: 10b9e5d0f947
Create Date: 2026-07-03 17:54:41.391855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb4d823b7339'
down_revision = '10b9e5d0f947'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
