"""add tags and time to transactions

Revision ID: bbb111tags0002
Revises: aaa000merge001
Create Date: 2026-07-11 20:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbb111tags0002'
down_revision = 'aaa000merge001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('time')
        batch_op.drop_column('tags')
    # ### end Alembic commands ###
