"""Add 5-stage pipeline tracking columns

Revision ID: c16625661111
Revises: 49e31aea00a0
Create Date: 2026-07-03 15:37:08.243030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c16625661111'
down_revision = '49e31aea00a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_contact_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_our_message_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_their_message_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('read_receipt_seen', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('follow_up_sent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('follow_up_sent')
        batch_op.drop_column('read_receipt_seen')
        batch_op.drop_column('last_their_message_at')
        batch_op.drop_column('last_our_message_at')
        batch_op.drop_column('first_contact_at')

    # ### end Alembic commands ###
