"""Add AnalysisReport table

Revision ID: dceaa7e4494b
Revises: c16625661111
Create Date: 2026-07-03 16:13:25.684546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dceaa7e4494b'
down_revision = 'c16625661111'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
